#!/bin/bash

# 28 October 2020
# 20-10-28

# Inrease the brightness of the display

if [[ ! $1 = "" && $1 -gt 0 && $1 -lt 256 ]]; then
  current=`cat /sys/class/backlight/amdgpu_bl0/brightness`
  
  echo `expr $current + $1` > /sys/class/backlight/amdgpu_bl0/brightness
else
  echo "Input a valid brightness value"
fi

exit 0
