#!/bin/bash

# 2 November 2020
# 20-11-2

# Toggle the touchpad on/off (https://wiki.archlinux.org/index.php/Touchpad_Synaptics#Software_toggle)

declare -i ID
ID=`xinput list | grep -Eio '(touchpad|glidepoint)\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}'`
declare -i STATE
STATE=`xinput list-props $ID|grep 'Device Enabled'|awk '{print $4}'`
if [ $STATE -eq 1 ]
then
  xinput disable $ID
  echo "Disabled touchpad"
  # notify-send -a 'Touchpad' 'Disabled' -i input-touchpad
else
  xinput enable $ID
  echo "Enabled touchpad"
  # notify-send -a 'Touchpad' 'Enabled' -i input-touchpad
fi
