#!/bin/bash

# Set backlight write permissions for the "video" group
echo "Setting backlight permissions..."
chown root:video /sys/class/backlight/amdgpu_bl0/brightness
chmod 664 /sys/class/backlight/amdgpu_bl0/brightness
echo "Backlight permissions set"

# Remove '$RECYCLE BIN' and 'SYSTEM VOLUME INFORMATION' from files partition (/files/)
echo "Removing Windows dirs from files..."

echo "Removed Windows dirs from files"

