#!/bin/bash

# 20 November 2020
# 20-11-20

# Restart keyboard if it gets stuck typing a key

# Needs to be run with root permissions

rmmod atkbd
modprobe atkbd reset=1

echo "Restarted keyboard"

#runuser -l anthony -c 'DISPLAY=":0" notify-send "Restarted keyboard"'
