#!/bin/bash

# 23-10-2020

# Set the brightness of the backlight (requires root permissions if autostart doesn't work properly)

if [[ ! $1 = "" && $1 -ge 0 && $1 -lt 256 ]]; then
  echo $1 > /sys/class/backlight/amdgpu_bl0/brightness
else
  echo "Input a valid brightness value"
fi

exit 0
