#!/bin/bash

# 23 October 2020
# 20-10-23

# Set the brightness of the backlight (requires root permissions if autostart doesn't work properly)

if [[ ! $1 = "" && $1 -gt 0 && $1 -lt 256 ]]; then
  echo $1 > /sys/class/backlight/amdgpu_bl0/brightness
else
  echo "Input a valid brightness value"
fi

exit 0
