#!/bin/bash

# 20-11-2022

# Set the speed of the fan (requires root permissions if autostart doesn't work properly)

if [[ ! $1 = "" && $1 -ge 0 && $1 -le 7 || $1 = "auto" ]]; then
  echo level $1 > /proc/acpi/ibm/fan
else
  echo "Input a value from 0-7, or \"auto\""
fi

exit 0
