#!/bin/bash

#6 November 2020
#20-11-6

# Print out common system information


# First print the date & time
date
echo "----------------"


# Temperatures:
#sens=$(sensors)
#thermals=$(cat /proc/acpi/ibm/thermal)
#thermals2=${thermals/	/        }
#gputemp=$(echo "$sens" | grep edge)
#gputemp2=${gputemp:15:6}
#ssdtemp=$(echo "$sens" | grep Composite)
#ssdtemp2=${ssdtemp:15:6}
#zentemp=$(echo "$sens" | grep Tdie)
#zentemp2=${zentemp:15:6}
#
##echo "ACPI ${thermals2/temp/Temp}"
#echo "CPU ${thermals2/temperatures:        /Temperature:          }"
#echo "GPU Temperature:          ${gputemp2}"
#echo "SSD Temperature:          ${ssdtemp2}"
#echo "ZEN Temperature:          ${zentemp2}"

thermals=$(cat /proc/acpi/ibm/thermal)
thermals2=${thermals/	/        }
echo "CPU ${thermals2/temperatures:        /Temperature:          }"

#rawtemp=$(cat /sys/class/hwmon/hwmon8/temp1_input)
rawtemp=$(cat /sys/class/drm/card0/device/hwmon/hwmon*/temp1_input)
printf "GPU Temperature:          "
printf ${rawtemp:0:2}
printf "."
printf $(($(($rawtemp / 100)) % 10))
echo " C"

#rawtemp=$(cat /sys/class/hwmon/hwmon2/temp1_input)
rawtemp=$(cat /sys/class/nvme/nvme0/hwmon*/temp1_input)
printf "SSD Temperature:          "
printf ${rawtemp:0:2}
printf "."
printf $(($(($rawtemp / 100)) % 10))
echo " C"

#rawtemp=$(cat /sys/class/hwmon/hwmon3/temp1_input)
rawtemp=$(cat /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon*/temp1_input)
printf "ZEN Temperature:          "
printf ${rawtemp:0:2}
printf "."
printf $(($(($rawtemp / 100)) % 10))
echo " C"

echo "----------------"


# Memory Info:
memory=($(free))
totalram=${memory[7]}
totalusedram=$(($totalram-${memory[9]}))
printf "Used Memory:              $((${memory[8]}/1024))/$(($totalram/1024)) MiB ($(($((${memory[8]}*100))/$totalram))%%)\n"
printf "Total Used Memory:        $(($totalusedram/1024))/$(($totalram/1024)) MiB ($(($(($totalusedram*100))/$totalram))%%)\n"

echo "----------------"


# GPU Info:
printf "GPU Usage:                $(cat /sys/class/drm/card0/device/gpu_busy_percent)%%\n"

totalvram=$(cat /sys/class/drm/card0/device/mem_info_vram_total)
usedvram=$(cat /sys/class/drm/card0/device/mem_info_vram_used)
printf "VRAM Usage:               $(($usedvram/1048576))/$(($totalvram/1048576)) MiB ($(($(($usedvram*100))/$totalvram))%%)\n"

echo "----------------"


# CPU Info:
#
#echo "----------------"


# Battery Info:
currentcap=$(expr `cat /sys/class/power_supply/BAT0/energy_full` / 1000)
currentenergy=$(expr `cat /sys/class/power_supply/BAT0/energy_now` / 1000)
currentpower=$(expr `cat /sys/class/power_supply/BAT0/power_now` / 1000)

printf "Current energy:           "
printf "$currentenergy mWh\n"

printf "Current power:            "
if [[ $(cat /sys/class/power_supply/BAT0/status) = "Discharging" ]]; then
  printf "-"
fi
printf "$currentpower mW\n"

printf "Charge:                   "
charge=$(($(($currentenergy*1000)) / $currentcap))
printf $(($charge / 10))
printf "."
printf $(($charge % 10))
printf "%%\n"

if [[ ! $currentpower = 0 ]]; then
  # Get the rough amount of time until empty (in tenths of hours)
  roughtime=$(($(($currentenergy*10)) / $currentpower))
  # If the battery state is "charging" calculate the rough amount of time until full (in tenths of hours)
  if [[ $(cat /sys/class/power_supply/BAT0/status) = "Charging" ]]; then
    roughtime=$(($(($(($currentcap-$currentenergy))*10)) / $currentpower))
  fi
  # Print the hours
  printf "Estimated time:           "
  printf $(($roughtime / 10))
  if [[ $(($roughtime / 10)) = 1 ]]; then
    printf " Hour "
  else
    printf " Hours "
  fi
  # Print the minutes
  printf "$(($(($roughtime % 10))*6))"
  printf " Minutes\n"
fi




exit 0









