# Bash configuration for Anthony Wilson



# Include the home bin directory in the path
export PATH=$PATH:/files/Code/bin

# Ignore duplicate commands when saving to bash history
export HISTCONTROL=ignoredups:erasedups
unset HISTFILESIZE
export HISTSIZE=2000

# Set the LC_ALL locale to C to prevent error messages
export LC_ALL=C;

# Only do the following if the shell is running interactively
[[ $- != *i* ]] && return



# Aliases:

#ls aliases
alias ls='ls --color=auto'
alias la='exa -a'
alias ll='exa -lg'
alias l='exa -alg'

#Navigation
alias ..='cd ..'
alias ~='cd ~'

#Grep aliases
alias grep='grep --color=auto'

#Ask before overwriting/removing a file
alias cp='cp -i' 
alias mv='mv -i'
alias rm='rm -i'

#Because I use this command all the time
alias x='startx'

#Pacman shortcuts
alias update='sudo update'
alias pac='sudo pacman'
alias updateaur='yay -Sua'

#Battery
alias battery='sudo tlp-stat -b'
alias setbat='sudo setchargethresholds'
alias hbat='setbat 40 50'

#System monitoring
alias sysmon='watch -n 0.5 -t sysinfo'
alias nload='nload wlp3s0 enp2s0f0 lo'

#Launch alsamixer focused on the correct sound card
alias audio='alsamixer -c 1'

#Save a few keypresses when shutting down (this is made redundant by WM keybind)
alias poweroff='shutdown now'

#Pause/resume a process
alias pause='kill -s SIGSTOP'
alias resume='kill -s SIGCONT'

#Run the autostart file manually
alias autostart='sh ~/.autostart.sh'

#Re-sync system & hardware clock
alias resetclock='sudo timedatectl set-ntp true && sudo hwclock --systohc && timedatectl'

#Clipboard/Primary buffer aliases
alias setclip='xclip -selection c'
alias getclip='xclip -selection c -o'
alias setprim='xclip -selection p'
alias getprim='xclip -selection p -o'
#alias copy='printf $1 | xclip -selection c'
alias paste='xclip -selection c -o'

#SSH server
alias startssh='sudo systemctl start sshd'
alias stopssh='sudo systemctl stop sshd'
alias logssh='journalctl -u sshd | tail -100 | less'

#Apache web server
alias startapache='sudo systemctl start httpd'
alias stopapache='sudo systemctl stop httpd'
alias logapache='tail -200 /var/log/httpd/access_log | less'
alias apachelog='tail -f /var/log/httpd/access_log'
alias apacheerrors='tail -f /var/log/httpd/error_log'

#MariaDB/MySQL database
alias startdb='sudo systemctl start mariadb'
alias stopdb='sudo systemctl stop mariadb'

#Mounting
alias mountwin='sudo mount /dev/nvme0n1p3 /windows -o umask=000'
alias umountwin='sudo umount /windows'
alias mountmint='sudo mount /dev/nvme0n1p8 /mnt/mint'
alias umountmint='sudo umount /mnt/mint'
alias pmount='sudo mount -o umask=000'
alias usermount='sudo mount -o umask=000'

#Empty Trash (Unecessary since I delete files directly)
#alias emptytrash='sudo rm -rf ~/.local/share/Trash/files/*; sudo rm -rf ~/.local/share/Trash/info/*'

#Faster way to use systemctl
alias susys='sudo systemctl'

#Clean up the permissions and extended attributes of ~/Files
alias cleanfiles='sudo cleansefiles'
alias cleansefiles='sudo cleansefiles'

#SSD TRIM alias
alias trim='sudo fstrim -v'


#Prepend 'sudo' to commands that always require root permissions
alias systemctl='sudo systemctl'
alias powertop='sudo powertop'
alias restartkeyboard='sudo restartkeyboard'
alias mount='sudo mount'
alias umount='sudo umount'
alias gparted='sudo gparted'
alias tlp-stat='sudo tlp-stat'



# PSx prompt formats:

#PS1='[\u@\h \W]\$ '     #Uppercase '\W' displays folder name
#PS1='[Anthony \w]\$ '   #Lowercase '\w' displays path
#PS1='[Anthony $PWD]\$ ' #Displays full directory path
#PS1='\e[31m[\e[32mAnthony \e[34m\w\e[31m]\$\e[0m '    #With colours
PS1='\[\e[0;31m\][\[\e[0;32m\]Anthony \[\e[0;34m\]\w\[\e[0;31m\]]\$\[\e[0m\] '    #With colours (proper formatting to give actual text length in shell)
